// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cards-redesign/AsymmetricSplit.tsx": () => import("../components/mockups/cards-redesign/AsymmetricSplit.tsx"),
  "./components/mockups/cards-redesign/MinimalLines.tsx": () => import("../components/mockups/cards-redesign/MinimalLines.tsx"),
  "./components/mockups/cards-redesign/VerticalRows.tsx": () => import("../components/mockups/cards-redesign/VerticalRows.tsx"),
  "./components/mockups/home-landing/BoldMinimal.tsx": () => import("../components/mockups/home-landing/BoldMinimal.tsx"),
  "./components/mockups/home-landing/CinematicSplit.tsx": () => import("../components/mockups/home-landing/CinematicSplit.tsx")
};
